#!/command/with-contenv bash
# shellcheck shell=bash
# Start the fake SecureVu service

set -o errexit -o nounset -o pipefail

# Tell S6-Overlay not to restart this service
s6-svc -O .

while true; do
  echo "[INFO] The fake SecureVu service is running..."
  sleep 5s
done
