blank_issues_enabled: false
contact_links:
  - name: SecureVu Support
    url: https://github.com/SecureCorp-Mexico/SecureVu2/discussions/new/choose
    about: Get support for setting up or troubleshooting SecureVu.
  - name: SecureVu Bug Report
    url: https://github.com/SecureCorp-Mexico/SecureVu2/discussions/new/choose
    about: Report a specific UI or backend bug.
