import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "category",
      label: "Auth",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/auth-auth-get",
          label: "Authenticate request",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/profile-profile-get",
          label: "Get user profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/logout-logout-get",
          label: "Logout user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/login-login-post",
          label: "Login with credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/get-users-users-get",
          label: "Get all users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/create-user-users-post",
          label: "Create new user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/delete-user-users-username-delete",
          label: "Delete user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "integrations/api/update-password-users-username-password-put",
          label: "Update user password",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "integrations/api/update-role-users-username-role-put",
          label: "Update user role",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Classification",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/get-faces-faces-get",
          label: "Get all registered faces",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/reclassify-face-faces-reprocess-post",
          label: "Reprocess a face training image",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/train-face-faces-train-name-classify-post",
          label: "Classify and save a face training image",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/create-face-faces-name-create-post",
          label: "Create a new face name",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/register-face-faces-name-register-post",
          label: "Register a face image",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/recognize-face-faces-recognize-post",
          label: "Recognize a face from an uploaded image",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/deregister-faces-faces-name-delete-post",
          label: "Delete face images",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/rename-face-faces-old-name-rename-put",
          label: "Rename a face name",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "integrations/api/reprocess-license-plate-lpr-reprocess-put",
          label: "Reprocess a license plate",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "integrations/api/reindex-embeddings-reindex-put",
          label: "Reindex embeddings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "integrations/api/transcribe-audio-audio-transcribe-put",
          label: "Transcribe audio",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "integrations/api/get-custom-attributes-classification-attributes-get",
          label: "Get custom classification attributes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/get-classification-dataset-classification-name-dataset-get",
          label: "Get classification dataset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/get-classification-images-classification-name-train-get",
          label: "Get classification train images",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/train-configured-model-classification-name-train-post",
          label: "Train a classification model",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/delete-classification-dataset-images-classification-name-dataset-category-delete-post",
          label: "Delete classification dataset images",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/categorize-classification-image-classification-name-dataset-categorize-post",
          label: "Categorize a classification image",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/delete-classification-train-images-classification-name-train-delete-post",
          label: "Delete classification train images",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Review",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/review-review-get",
          label: "Review",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/review-ids-review-ids-get",
          label: "Review Ids",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/review-summary-review-summary-get",
          label: "Review Summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/set-multiple-reviewed-reviews-viewed-post",
          label: "Set Multiple Reviewed",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/delete-reviews-reviews-delete-post",
          label: "Delete Reviews",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/motion-activity-review-activity-motion-get",
          label: "Motion Activity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/get-review-from-event-review-event-event-id-get",
          label: "Get Review From Event",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/get-review-review-review-id-get",
          label: "Get Review",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/set-not-reviewed-review-review-id-viewed-delete",
          label: "Set Not Reviewed",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "integrations/api/generate-review-summary-review-summarize-start-start-ts-end-end-ts-post",
          label: "Generate Review Summary",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "App",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/is-healthy-get",
          label: "Is Healthy",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/config-schema-config-schema-json-get",
          label: "Config Schema",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/go-2-rtc-streams-go-2-rtc-streams-get",
          label: "Go2Rtc Streams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/go-2-rtc-camera-stream-go-2-rtc-streams-camera-name-get",
          label: "Go2Rtc Camera Stream",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/version-version-get",
          label: "Version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/stats-stats-get",
          label: "Stats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/stats-history-stats-history-get",
          label: "Stats History",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/metrics-metrics-get",
          label: "Metrics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/config-config-get",
          label: "Config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/config-raw-config-raw-get",
          label: "Config Raw",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/config-save-config-save-post",
          label: "Config Save",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/config-set-config-set-put",
          label: "Config Set",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "integrations/api/ffprobe-ffprobe-get",
          label: "Ffprobe",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/vainfo-vainfo-get",
          label: "Vainfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/nvinfo-nvinfo-get",
          label: "Nvinfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/logs-logs-service-get",
          label: "Logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/restart-restart-post",
          label: "Restart",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/get-labels-labels-get",
          label: "Get Labels",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/get-sub-labels-sub-labels-get",
          label: "Get Sub Labels",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/plus-models-plus-models-get",
          label: "Plusmodels",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/get-recognized-license-plates-recognized-license-plates-get",
          label: "Get Recognized License Plates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/timeline-timeline-get",
          label: "Timeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/hourly-timeline-timeline-hourly-get",
          label: "Hourly Timeline",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Logs",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/logs-logs-service-get",
          label: "Logs",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Preview",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/preview-ts-preview-camera-name-start-start-ts-end-end-ts-get",
          label: "Get preview clips for time range",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/preview-hour-preview-year-month-day-hour-camera-name-tz-name-get",
          label: "Get preview clips for specific hour",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/get-preview-frames-from-cache-preview-camera-name-start-start-ts-end-end-ts-frames-get",
          label: "Get cached preview frame filenames",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Notifications",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/get-vapid-pub-key-notifications-pubkey-get",
          label: "Get VAPID public key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/register-notifications-notifications-register-post",
          label: "Register notifications",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Export",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/get-exports-exports-get",
          label: "Get exports",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/export-recording-export-camera-name-start-start-time-end-end-time-post",
          label: "Start recording export",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/export-rename-export-event-id-rename-patch",
          label: "Rename export",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "integrations/api/export-delete-export-event-id-delete",
          label: "Delete export",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "integrations/api/get-export-exports-export-id-get",
          label: "Get a single export",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Events",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/events-events-get",
          label: "Get events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/events-explore-events-explore-get",
          label: "Get summary of objects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/event-ids-event-ids-get",
          label: "Get events by ids",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/events-search-events-search-get",
          label: "Search events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/events-summary-events-summary-get",
          label: "Events Summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/event-events-event-id-get",
          label: "Get event by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/delete-event-events-event-id-delete",
          label: "Delete event",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "integrations/api/set-retain-events-event-id-retain-post",
          label: "Set event retain indefinitely",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/delete-retain-events-event-id-retain-delete",
          label: "Stop event from being retained indefinitely",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "integrations/api/send-to-plus-events-event-id-plus-post",
          label: "Send event to SecureVu+",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/false-positive-events-event-id-false-positive-put",
          label: "Submit false positive to SecureVu+",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "integrations/api/set-sub-label-events-event-id-sub-label-post",
          label: "Set event sub label",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/set-plate-events-event-id-recognized-license-plate-post",
          label: "Set event license plate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/set-attributes-events-event-id-attributes-post",
          label: "Set custom classification attributes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/set-description-events-event-id-description-post",
          label: "Set event description",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/regenerate-description-events-event-id-description-regenerate-put",
          label: "Regenerate event description",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "integrations/api/generate-description-embedding-description-generate-post",
          label: "Generate description embedding",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/delete-events-events-delete",
          label: "Delete events",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "integrations/api/create-event-events-camera-name-label-create-post",
          label: "Create manual event",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/end-event-events-event-id-end-put",
          label: "End manual event",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "integrations/api/create-trigger-embedding-trigger-embedding-post",
          label: "Create trigger embedding",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/update-trigger-embedding-trigger-embedding-camera-name-name-put",
          label: "Update trigger embedding",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "integrations/api/delete-trigger-embedding-trigger-embedding-camera-name-name-delete",
          label: "Delete trigger embedding",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "integrations/api/get-triggers-status-triggers-status-camera-name-get",
          label: "Get triggers status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Media",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/mjpeg-feed-camera-name-get",
          label: "Mjpeg Feed",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/camera-ptz-info-camera-name-ptz-info-get",
          label: "Camera Ptz Info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/latest-frame-camera-name-latest-extension-get",
          label: "Latest Frame",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/get-snapshot-from-recording-camera-name-recordings-frame-time-snapshot-format-get",
          label: "Get Snapshot From Recording",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/submit-recording-snapshot-to-plus-camera-name-plus-frame-time-post",
          label: "Submit Recording Snapshot To Plus",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "integrations/api/get-recordings-storage-usage-recordings-storage-get",
          label: "Get Recordings Storage Usage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/all-recordings-summary-recordings-summary-get",
          label: "All Recordings Summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/recordings-summary-camera-name-recordings-summary-get",
          label: "Recordings Summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/recordings-camera-name-recordings-get",
          label: "Recordings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/no-recordings-recordings-unavailable-get",
          label: "No Recordings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/recording-clip-camera-name-start-start-ts-end-end-ts-clip-mp-4-get",
          label: "Recording Clip",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/vod-ts-vod-camera-name-start-start-ts-end-end-ts-get",
          label: "Vod Ts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/vod-hour-no-timezone-vod-year-month-day-hour-camera-name-get",
          label: "Vod Hour No Timezone",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/vod-hour-vod-year-month-day-hour-camera-name-tz-name-get",
          label: "Vod Hour",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/vod-event-vod-event-event-id-get",
          label: "Vod Event",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/event-snapshot-events-event-id-snapshot-jpg-get",
          label: "Event Snapshot",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/event-thumbnail-events-event-id-thumbnail-extension-get",
          label: "Event Thumbnail",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/grid-snapshot-camera-name-grid-jpg-get",
          label: "Grid Snapshot",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/event-snapshot-clean-events-event-id-snapshot-clean-png-get",
          label: "Event Snapshot Clean",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/event-clip-events-event-id-clip-mp-4-get",
          label: "Event Clip",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/event-preview-events-event-id-preview-gif-get",
          label: "Event Preview",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/preview-gif-camera-name-start-start-ts-end-end-ts-preview-gif-get",
          label: "Preview Gif",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/preview-mp-4-camera-name-start-start-ts-end-end-ts-preview-mp-4-get",
          label: "Preview Mp4",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/review-preview-review-event-id-preview-get",
          label: "Review Preview",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/preview-thumbnail-preview-file-name-thumbnail-webp-get",
          label: "Preview Thumbnail",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/preview-thumbnail-preview-file-name-thumbnail-jpg-get",
          label: "Preview Thumbnail",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/label-thumbnail-camera-name-label-thumbnail-jpg-get",
          label: "Label Thumbnail",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/label-thumbnail-camera-name-label-best-jpg-get",
          label: "Label Thumbnail",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/label-clip-camera-name-label-clip-mp-4-get",
          label: "Label Clip",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "integrations/api/label-snapshot-camera-name-label-snapshot-jpg-get",
          label: "Label Snapshot",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "integrations/api/schemas/appconfigsetbody",
          label: "AppConfigSetBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/apppostloginbody",
          label: "AppPostLoginBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/apppostusersbody",
          label: "AppPostUsersBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/appputpasswordbody",
          label: "AppPutPasswordBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/appputrolebody",
          label: "AppPutRoleBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/audiotranscriptionbody",
          label: "AudioTranscriptionBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/body-recognize-face-faces-recognize-post",
          label: "Body_recognize_face_faces_recognize_post",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/body-register-face-faces-name-register-post",
          label: "Body_register_face_faces__name__register_post",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/dayreview",
          label: "DayReview",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/deletefaceimagesbody",
          label: "DeleteFaceImagesBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventcreateresponse",
          label: "EventCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventmultideleteresponse",
          label: "EventMultiDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventresponse",
          label: "EventResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventuploadplusresponse",
          label: "EventUploadPlusResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventscreatebody",
          label: "EventsCreateBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventsdeletebody",
          label: "EventsDeleteBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventsdescriptionbody",
          label: "EventsDescriptionBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventsendbody",
          label: "EventsEndBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventslprbody",
          label: "EventsLPRBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventssublabelbody",
          label: "EventsSubLabelBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/eventsattributesbody",
          label: "EventsAttributesBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/exportmodel",
          label: "ExportModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/exportrecordingsbody",
          label: "ExportRecordingsBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/exportrenamebody",
          label: "ExportRenameBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/extension",
          label: "Extension",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/facerecognitionresponse",
          label: "FaceRecognitionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/facesresponse",
          label: "FacesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/genericresponse",
          label: "GenericResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/httpvalidationerror",
          label: "HTTPValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/last-24-hoursreview",
          label: "Last24HoursReview",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/playbackfactorenum",
          label: "PlaybackFactorEnum",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/playbacksourceenum",
          label: "PlaybackSourceEnum",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/previewmodel",
          label: "PreviewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/regeneratedescriptionenum",
          label: "RegenerateDescriptionEnum",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/renamefacebody",
          label: "RenameFaceBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/reviewactivitymotionresponse",
          label: "ReviewActivityMotionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/reviewmodifymultiplebody",
          label: "ReviewModifyMultipleBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/reviewsegmentresponse",
          label: "ReviewSegmentResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/reviewsummaryresponse",
          label: "ReviewSummaryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/severityenum",
          label: "SeverityEnum",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/startexportresponse",
          label: "StartExportResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/submitplusbody",
          label: "SubmitPlusBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/triggerembeddingbody",
          label: "TriggerEmbeddingBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/triggertype",
          label: "TriggerType",
          className: "schema",
        },
        {
          type: "doc",
          id: "integrations/api/schemas/validationerror",
          label: "ValidationError",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
